trigger:
  batch: true
  paths:
    exclude:
    - CHANGELOG.md
    - LICENSE
    - README.md

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  maxParallel: 3
  matrix:
    Node 6:
      node_version: 6.x
    Node 8:
      node_version: 8.x
    Node 10:
      node_version: 10.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'

- script: yarn install --ignore-engines
  displayName: 'Install Dependencies'

- script: yarn lint
  displayName: 'Lint JavaScript Code'

- script: yarn test
  displayName: 'Run Unit Tests'

- task: PublishTestResults@2
  displayName: 'Publish test results (Azure Pipelines)'
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'test/junit-results.xml'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage results (Azure Pipelines)'
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'

- script: yarn coverage
  displayName: 'Publish code coverage results (coveralls.io)'
